// src/types/index.ts - Main export file

// User Types
export type {
  UserRole,
  UserStatus,
  AccountStatus,
  BaseUser,
  AdminUser,
  EmployeeUser,
  ManagerUser,
  GuestUser,
  UserStats,
  UserFilters,
  Permission,
  UserAction,
  EmergencyContact,
  UserProfile,
  UserPreferences,
  ReservationSummary,
} from "./user.types";

// Room Types
export type {
  RoomType,
  RoomStatus,
  RoomCapacityType,
  Room,
  Building,
  Floor,
  RoomAmenity,
  RoomAvailability,
  DayAvailability,
  TimeBreak,
  HolidaySchedule,
  SpecialDateSchedule,
  OperatingHours,
  BookingPolicy,
  CancelationPolicy,
  NoShowPolicy,
  BookingRestriction,
  MaintenanceSchedule,
  RoomFilters,
  RoomStats,
  PopularRoom,
} from "./room.types";

// Reservation Types
export type {
  ReservationStatus,
  RecurrenceType,
  ReservationPriority,
  BookingSource,
  Reservation,
  ReservationAttendee,
  RecurrencePattern,
  EquipmentReservation,
  RoomSetup,
  CateringRequest,
  ServiceRequest,
  ReservationApproval,
  ReservationNotification,
  ReservationFeedback,
  BillingInfo,
  TimeSlot,
  BookingRequest,
  ReservationFilters,
  ReservationStats,
  PeakHour,
} from "./reservation.types";

// Equipment Types
export type {
  EquipmentType,
  EquipmentStatus,
  EquipmentCondition,
  Equipment,
  EquipmentSpecification,
  EquipmentAccessory,
  EquipmentManual,
  EquipmentMaintenance,
  EquipmentReservationHistory,
  EquipmentRestriction,
  EquipmentFilters,
  EquipmentStats,
  PopularEquipment,
} from "./equipment.types";

// System Types
export type {
  SystemSettings,
  Address,
  ContactInfo,
  Holiday,
  BookingSettings,
  NotificationSettings,
  AdminNotificationSettings,
  NotificationTemplate,
  SecuritySettings,
  PasswordPolicy,
  IntegrationSettings,
  CalendarIntegration,
  EmailProvider,
  SMSProvider,
  SSOProvider,
  APIKey,
  Webhook,
  AnalyticsData,
  AnalyticsMetric,
  ChartDataPoint,
  SystemHealth,
  HealthCheck,
  SystemExport,
  SystemStats,
  AuditLog,
  ErrorLog,
  BackupInfo,
  FeatureFlag,
  SystemMaintenance,
} from "./system.types";
